name: papyrus_android
description: Android System WebView implementation for Papyrus.
version: 0.1.0
homepage: https://github.com/dizitart/papyrus
repository: https://github.com/dizitart/papyrus/tree/main/packages/papyrus_android
issue_tracker: https://github.com/dizitart/papyrus/issues

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  papyrus_platform_interface:
    path: ../papyrus_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: papyrus
    platforms:
      android:
        package: dev.papyrus.papyrus_android
        pluginClass: PapyrusAndroidPlugin
        dartPluginClass: PapyrusAndroid

