name: papyrus_platform_interface
description: Shared platform interface and data contracts for Papyrus.
version: 0.1.1
homepage: https://github.com/dizitart/papyrus
repository: https://github.com/dizitart/papyrus
issue_tracker: https://github.com/dizitart/papyrus/issues

environment:
  sdk: ^3.11.0

dependencies:
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  test: ^1.26.0
  lints: ^6.0.0

