name: papyrus_example
description: Example application for Papyrus.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  papyrus:
    path: ../../packages/papyrus

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
